In [1]:
import torch

/root/miniconda3/envs/ndc/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
a = torch.arange(10).reshape(2,5).float()
a

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])

In [3]:
b = torch.zeros(3, 5)
b

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [4]:
index=torch.LongTensor([[1, 2, 1, 1, 2],
                        [2, 0, 2, 1, 0]])
print(index)
b_= b.scatter(dim=0, index=index, src=a)
print(b_)

# tensor([[0, 6, 0, 0, 9],
#        [0, 0, 2, 8, 0],
#        [5, 1, 7, 0, 4]])

tensor([[1, 2, 1, 1, 2],
        [2, 0, 2, 1, 0]])
tensor([[0., 6., 0., 0., 9.],
        [0., 0., 2., 8., 0.],
        [5., 1., 7., 0., 4.]])


In [5]:
from torch_scatter import scatter_max

ModuleNotFoundError: No module named 'torch_scatter'